# Generated by Django 4.2.5 on 2023-12-27 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_liked_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
