# Generated by Django 4.2.5 on 2024-01-17 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
                ('listName', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile-pics/default.jpg', upload_to='profile-pics'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('timeCompleted', models.DateTimeField(blank=True, null=True)),
                ('completedStatus', models.BooleanField(default=False)),
                ('timeAlertedIssue', models.DateTimeField(blank=True, null=True)),
                ('issueStatus', models.BooleanField(default=False)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='checklist.list')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
