# Generated by Django 4.2.5 on 2024-01-17 01:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_list_user_picture_task_list_collaborators_list_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborations', to=settings.AUTH_USER_MODEL),
        ),
    ]
