# Generated by Django 4.2.5 on 2024-02-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_alter_list_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importantFlag',
            field=models.BooleanField(default=False),
        ),
    ]
