# Generated by Django 4.2.5 on 2024-02-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_task_alertedby_task_completedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='statusMessage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
