# Generated by Django 4.2.5 on 2024-02-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_task_statusmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='statusMessage',
        ),
    ]
