# Generated by Django 4.2.5 on 2024-02-10 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_issue_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='timeResolved',
        ),
        migrations.AddField(
            model_name='issue',
            name='reportedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='timeReported',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
