# Generated by Django 4.2.5 on 2024-02-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0010_remove_issue_timeresolved_issue_reportedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='importance',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='severity',
            field=models.TextField(),
        ),
    ]
