# Generated by Django 4.2.5 on 2024-02-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0011_alter_issue_importance_alter_issue_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='timeResolved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
